/*
 * File: app/view/ui/LoginContainer.js
 * Date: Thu Mar 12 2015 14:36:14 GMT-0400 (EDT)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PublishingWizard.ui.LoginContainer', {
    extend: 'Ext.container.ButtonGroup',

    frame: false,
    minHeight: 90,
    id: 'idLoginContainer',
    cls: 'itemLoginContainer',
    itemId: 'itemLoginContainer',
    margin: 4,
    maxWidth: 200,
    minWidth: 200,
    padding: 4,
    width: 300,
    title: 'anonymous',
    columns: 1,

    initComponent: function () {
        var me = this;

        Ext.applyIf(me, {
            layout: {
                columns: 1,
                type: 'table'
            },
            items: [
                {
                    xtype: 'button',
                    id: 'idLoginButton',
                    itemId: 'itemLoginButton',
                    margin: 1,
                    focusOnToFront: false,
                    focusCls: ' ',
                    text: 'Login'
                },
                {
                    xtype: 'button',
                    id: 'idAccountButton',
                    itemId: 'itemAccountButton',
                    margin: 1,
                    focusCls: ' ',
                    text: 'Account Info'
                },
                {
                    xtype: 'button',
                    id: 'idHelpButton',
                    itemId: 'itemHelpButton',
                    margin: 1,
                    focusCls: ' ',
                    text: 'Help'
                }
            ]
        });

        me.callParent(arguments);
    }
});