//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.0.3705.288.
// 
namespace oai {
    using System.Xml.Serialization;
	/// <summary>
	/// OAI definition
	/// </summary>
	///Current version
	///ID:		$Id: OAI-PMH.cs,v 1.1.1.1 2005/05/05 15:17:01 grgreene Exp $
	///Revision:	$Revision: 1.1.1.1 $
	///Date:	$Date: 2005/05/05 15:17:01 $
	/// 
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="OAI-PMHtype", Namespace="http://www.openarchives.org/OAI/2.0/")]
  	[System.Xml.Serialization.XmlRootAttribute("OAI-PMH", Namespace="http://www.openarchives.org/OAI/2.0/", IsNullable=false)]

    public class OAIPMHtype {
        
		[System.Xml.Serialization.XmlAttribute()]
		public string schemaLocation = "http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd";
        /// <remarks/>
        public System.DateTime responseDate = System.DateTime.Now;
        
        /// <remarks/>
        public requestType request;
        
        /// <remarks/>

        [System.Xml.Serialization.XmlElementAttribute("error", typeof(OAIPMHerrorType))]
        [System.Xml.Serialization.XmlElementAttribute("Identify", typeof(IdentifyType))]
        [System.Xml.Serialization.XmlElementAttribute("ListMetadataFormats", typeof(metadataFormatType[]))]
        [System.Xml.Serialization.XmlElementAttribute("ListSets", typeof(ListSetsType))]
        [System.Xml.Serialization.XmlElementAttribute("GetRecord", typeof(GetRecordType))]
        [System.Xml.Serialization.XmlElementAttribute("ListIdentifiers", typeof(ListIdentifiersType))]
        [System.Xml.Serialization.XmlElementAttribute("ListRecords", typeof(ListRecordsType))]
        public object[] Items;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class requestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public verbType verb;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool verbSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string identifier;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string metadataPrefix;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string from;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string until;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string set;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resumptionToken;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public enum verbType {
        
        /// <remarks/>
        Identify,
        
        /// <remarks/>
        ListMetadataFormats,
        
        /// <remarks/>
        ListSets,
        
        /// <remarks/>
        GetRecord,
        
        /// <remarks/>
        ListIdentifiers,
        
        /// <remarks/>
        ListRecords,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class ListRecordsType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("record")]
        public recordType[] record;
        
        /// <remarks/>
        public resumptionTokenType resumptionToken;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class recordType {
        
        /// <remarks/>
        public headerType header;
        
        /// <remarks/>
        public System.Xml.XmlElement metadata;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("about")]
        public System.Xml.XmlElement[] about;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class headerType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string identifier;
        
        /// <remarks/>
        public string datestamp;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("setSpec")]
        public string[] setSpec;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public statusType status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public enum statusType {
        
        /// <remarks/>
        okay,
        deleted
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class resumptionTokenType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime expirationDate;


        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirationDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
        public string completeListSize;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="nonNegativeInteger")]
        public string cursor;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;

        public resumptionTokenType()
        {
            expirationDateSpecified = false;
        }


        public resumptionTokenType(resumptionTokenType orig)
        {
            expirationDate = orig.expirationDate;
            expirationDateSpecified = orig.expirationDateSpecified;
            completeListSize = orig.completeListSize;
            cursor = orig.cursor;
            Value = orig.Value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class ListIdentifiersType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("header")]
        public headerType[] header;
        
        /// <remarks/>
        public resumptionTokenType resumptionToken;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class GetRecordType {
        
        /// <remarks/>
        public recordType record;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class setType {
        
        /// <remarks/>
        public string setSpec;
        
        /// <remarks/>
        public string setName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("setDescription")]
        public System.Xml.XmlElement[] setDescription;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class ListSetsType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("set")]
        public setType[] set;
        
        /// <remarks/>
        public resumptionTokenType resumptionToken;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute("metadataFormat", Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class metadataFormatType {
        
        /// <remarks/>
        public string metadataPrefix;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string schema;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string metadataNamespace;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class IdentifyType {
        
        /// <remarks/>
        public string repositoryName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string baseURL;
        
        /// <remarks/>
        public IdentifyTypeProtocolVersion protocolVersion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("adminEmail")]
        public string[] adminEmail;
        
        /// <remarks/>
        public string earliestDatestamp;
        
        /// <remarks/>
        public deletedRecordType deletedRecord;
        
        /// <remarks/>
        public granularityType granularity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("compression")]
        public string[] compression;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public System.Xml.XmlElement[] description;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public enum IdentifyTypeProtocolVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.0")]
        Item20,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public enum deletedRecordType {
        
        /// <remarks/>
        no,
        
        /// <remarks/>
        persistent,
        
        /// <remarks/>
        transient,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openarchives.org/OAI/2.0/")]
    public enum granularityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("YYYY-MM-DD")]
        YYYYMMDD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("YYYY-MM-DDThh:mm:ssZ")]
        YYYYMMDDThhmmssZ,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="OAI-PMHerrorType", Namespace="http://www.openarchives.org/OAI/2.0/")]
    public class OAIPMHerrorType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OAIPMHerrorcodeType code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="OAI-PMHerrorcodeType", Namespace="http://www.openarchives.org/OAI/2.0/")]
    public enum OAIPMHerrorcodeType {
        
        /// <remarks/>
        cannotDisseminateFormat,
        
        /// <remarks/>
        idDoesNotExist,
        
        /// <remarks/>
        badArgument,
        
        /// <remarks/>
        badVerb,
        
        /// <remarks/>
        noMetadataFormats,
        
        /// <remarks/>
        noRecordsMatch,
        
        /// <remarks/>
        badResumptionToken,
        
        /// <remarks/>
        noSetHierarchy,
    }
}
/* Log of changes
 * $Log: OAI-PMH.cs,v $
 * Revision 1.1.1.1  2005/05/05 15:17:01  grgreene
 * import
 *
 * Revision 1.4  2005/03/17 20:54:07  womullan
 * oai fixing
 *
 * Revision 1.3  2004/05/06 16:15:41  womullan
 *  some mods to main page - replication fixed
 *
 * Revision 1.2  2004/03/12 19:15:49  womullan
 * added keyword search to form
 *
 *
 * 
 * */
